site_name: My Docs
site_name: Blacksburg on a Budget
site_url: https://carolrector.github.io/site
theme:
  name: material
nav:
  - Blacksburg Eats: "index.md"
  - On a Budget: "budget.md"
  - Late Night Bite: "latenight.md"
  - Health Grind: "health.md"
  - On a Date: "date.md"
  - Honorable Mentions: "hm.md"
  - Conclusion: "conclusion.md"




  